version: "3"

services:
  caddy:
    image: caddy
    container_name: caddy
    hostname: caddy
    restart: unless-stopped
    networks:
      - caddy-network
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data/:/etc/caddy/
      - ./files/:/usr/share/caddy/
      - /srv/www/long-dair.com/html:/long-dair-html
    ports:
      - 80:80
      - 443:443

networks:
  caddy-network:
    external: true
