version: '3'

services:
  dobercorgi_backend:
    container_name: dobercorgi_backend
    image: registry.digitalocean.com/lewis/backend.dobercorgi.info:latest
    restart: unless-stopped
    networks:
      - caddy-network
    volumes:
      - ./logs:/var/www/html/storage/logs
      - ./config/.env:/var/www/html/.env

networks:
  caddy-network:
    external: true
